version: '2.3'
services:
    run:
        build: ./Docker
        runtime: nvidia
        ipc: host
        tty: true
        volumes:
            - ./dataset:/workspace/dataset
            - ./checkpoint:/workspace/checkpoint
            - ./net:/workspace/net
            - ./result:/workspace/result
            - ./tools:/workspace/tools
            - ./video:/workspace/video
            - ./vgg19_weight:/workspace/vgg19_weight
            - ./main.py:/workspace/main.py
            - ./test.py:/workspace/test.py
            - ./AnimeGAN.py:/workspace/AnimeGAN.py
